#
# Outbreak rating (metric)
#
# A metric that describes the outbreak magnitude of a particular point in time. 
#  "outbreak rating" is a general metric and only looks at one particular 
#  dimension. While it could be thought that a higher outbreak rating means more
#  deaths and more chance of spread, this kind of assumption is not ideal since 
#  the metric doesn't take into account other factors that influence this. 
#  For example, outbreak rating directly measures the new cases per 100k people 
#  (with a max limit). A higher number of new cases will mean that there is a 
#  higher chance that someone in this population will catch it. But it doesn't 
#  take into account many significant factors such as where the outbreaks are in
#  the country or if there are any restrictions or stay at home orders.
# Therefore this outbreak metric should be thought of as a direct measure of 
#  what it is, which is the new cases to population ratio, rather than risk of 
#  spread or risk of death.
#


#' Generates a dataset including daily outbreak ratings.
#' 
#' @param daily_cases data frame: includes DATE_REPOTED, COUNTRY_CODE and NEW_CASES columns
#' @param population: data frame: includes DATE_REPOTED, COUNTRY_CODE and POPULATION columns
#' 
#' @returns tibble dataset with date, country, outbreak rating and outbreak description
#' 
#' @seealso `calculate_outbreak_rating`, `describe_outbreak`
#' 
#' @examples
#' \dontrun{
#' daily_cases <- get_daily_cases()
#' population  <- get_population()
#' outbreak_ratings = generate_daily_outbreak_ratings(daily_cases, population)
#' }
generate_daily_outbreak_ratings <- function(daily_cases, population) {
    checkmate::assert_tibble(daily_cases)
    checkmate::assert_tibble(population)
    
    population_sel <- population %>% dplyr::select(DATE_REPORTED, COUNTRY_CODE, COUNTRY, POPULATION)
    
    daily_cases_sel <- daily_cases %>% dplyr::select(DATE_REPORTED, COUNTRY_CODE, NEW_CASES)
    
    daily_outbreak_ratings <- dplyr::left_join(daily_cases_sel, population_sel, by = c("DATE_REPORTED", "COUNTRY_CODE")) %>% 
        dplyr::mutate(OUTBREAK_RATING = calculate_outbreak_rating(new_cases = NEW_CASES, population = POPULATION)) %>% 
        dplyr::mutate(OUTBREAK_DESC = describe_outbreak(OUTBREAK_RATING))
    
    return(daily_outbreak_ratings)
}


#' Calculates the outbreak rating based on new cases to population ratio.
#' 
#' @param new_cases numeric: number of newly reported cases
#' @param population: numeric: population at the time of newly reported cases
#' 
#' @returns integer between 0 and 100
#' 
#' @seealso `generate_daily_outbreak_ratings`, `describe_outbreak`
#' 
#' @examples
#' \dontrun{
#' outbreak_rating <- calculate_outbreak_rating(new_cases = 25, population = 100000)
#' }
calculate_outbreak_rating <- function(new_cases, population) {
    checkmate::assert_numeric(new_cases)
    checkmate::assert_numeric(population)
    
    per_x_population <- 100000
    min_rating <- 0
    max_rating <- 100
    unknown_rating <- NA_integer_
    
    outbreak_rating <- per_x_population*(new_cases/population)
    outbreak_rating <- ifelse(is.infinite(outbreak_rating), unknown_rating, outbreak_rating)
    outbreak_rating <- ifelse(outbreak_rating < min_rating, min_rating, outbreak_rating)
    outbreak_rating <- ifelse(outbreak_rating > max_rating, max_rating, outbreak_rating)
    outbreak_rating <- round(outbreak_rating, 0)
    
    return(outbreak_rating)
}


#' Generates a description based on the outbreak rating.
#' 
#' @description Based on thresholds.
#' 
#' @param outbreak_rating integer: outbreak rating generated by `calculate_outbreak_rating`
#' 
#' @returns string describing the outbreak rating
#' 
#' @seealso `generate_daily_outbreak_ratings`, `calculate_outbreak_rating`
#' 
#' @examples
#' \dontrun{
#' describe_outbreak(c(0, 1, 29, 100, -1))
#' }
describe_outbreak <- function(outbreak_rating) {
    checkmate::assert_numeric(outbreak_rating, null.ok = TRUE)
    
    thresholds <- c(0             , 1    , 10   , 20    , 30, .Machine$integer.max)
    labels     <- c("No new cases", "Low", "Medium", "High", "Extreme")
    output <- as.character(cut(outbreak_rating, breaks = thresholds, labels = labels, right = FALSE))
    
    return(output)
}
